CREATE DATABASE sales_project;
USE sales_project;

DROP DATABASE sales_project;
SHOW DATABASES;



SHOW TABLES;
SELECT * FROM USERS ;
SELECT * FROM REVIEWS;
SELECT * FROM PRODUCTS;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_ITEMS;
SELECT * FROM EVENTS;


SELECT 'USERS' AS TABLE_NAME, COUNT(*) FROM USERS
UNION
SELECT 'PRODUCTS', COUNT(*) FROM PRODUCTS
UNION
SELECT 'ORDERS', COUNT(*) FROM ORDERS
UNION
SELECT 'ORDER_ITEMS', COUNT(*) FROM ORDER_ITEMS
UNION
SELECT 'REVIEWS', COUNT(*) FROM REVIEWS
UNION
SELECT 'EVENTS', COUNT(*) FROM EVENTS;

#WHAT IS TOTAL SALES?
SELECT ROUND(SUM(ITEM_PRICE*QUANTITY),0) AS TOTAL_SALES
FROM ORDER_ITEMS;

#HOW MANY TOTAL ORDERS ARE PLACED?
SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM ORDERS;

#HOW MANY TOTAL USERS?
SELECT COUNT(DISTINCT USER_ID) AS TOTAL_USERS
FROM USERS;

#WHAT IS AVERAGE ORDER VALUE?
SELECT ROUND(SUM(OI.QUANTITY*OI.ITEM_PRICE) /  COUNT(DISTINCT O.ORDER_ID),2) AS AVG
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID;


#WHAT IS DAILY SALES TREND?
SELECT O.ORDER_DATE , SUM(OI.QUANTITY*OI.ITEM_PRICE) AS DAILY_SALES
FROM ORDERS O
JOIN ORDER_ITEMS OI
on O.ORDER_ID = OI.ORDER_ID
GROUP BY O.ORDER_DATE;


#WHAT IS MONTHLY SALES TREND?
       ## JAN-FEB
SELECT MONTHNAME(O.ORDER_DATE) AS MONTH_NAME,ROUND(SUM(OI.QUANTITY*OI.ITEM_PRICE),2) AS TOTAL_SALES
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY MONTHNAME(O.ORDER_DATE);


       ##1-12
SELECT MONTH(O.ORDER_DATE) AS MONTH_NAME,COUNT(OI.QUANTITY*OI.ITEM_PRICE) AS TOTAL_ORDERS
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY MONTH(O.ORDER_DATE)
ORDER BY  MONTH(O.ORDER_DATE);

#TOP SELLING PRODUCTS?
SELECT P.PRODUCT_NAME,SUM(OI.QUANTITY) AS TOTAL_UNITS_SOLD, SUM(OI.QUANTITY * OI.ITEM_PRICE) AS REVENUE
FROM ORDER_ITEMS OI
JOIN PRODUCTS P
ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY  P.PRODUCT_NAME 
ORDER BY P.PRODUCT_NAME DESC LIMIT 5;

#BOTTOM SELLING PRODUCTS?
SELECT P.PRODUCT_NAME,SUM(OI.QUANTITY) AS TOTAL_UNITS_SOLD, SUM(OI.QUANTITY * OI.ITEM_PRICE) AS REVENUE
FROM ORDER_ITEMS OI
JOIN PRODUCTS P
ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY  P.PRODUCT_NAME 
ORDER BY P.PRODUCT_NAME ASC LIMIT 5;

#CATEGORY-WISE SALES?
SELECT P.CATEGORY , SUM(OI.QUANTITY*OI.ITEM_PRICE) AS REVENUE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID 
GROUP BY P.CATEGORY
ORDER BY P.CATEGORY DESC;

#CITY-WISE SALES?
SELECT U.CITY , ROUND(SUM(OI.QUANTITY*OI.ITEM_PRICE),2) AS REVENUE
FROM USERS U
JOIN ORDER_ITEMS OI
ON U.USER_ID = OI.USER_ID
GROUP BY U.CITY;



#REPEAT CUSTOMERS?
SELECT USER_ID , COUNT(ORDER_ID) AS REPEATED_CUSTOMERS
FROM ORDERS
GROUP BY USER_ID
HAVING COUNT(ORDER_ID) > 1;	

#AVERAGE  CUSTOMER RATING PER PRODUCT?
SELECT P.PRODUCT_NAME, AVG(R.RATING) AS AVG_RATING
FROM PRODUCTS P
JOIN REVIEWS R
ON P.PRODUCT_ID = R.PRODUCT_ID
GROUP BY PRODUCT_NAME;

#WHICH PRODUCTS HAVE AN AVERAGE CUSTOMER RATING BELOW 3?
SELECT P.PRODUCT_NAME , AVG(R.RATING) AS AVG_RATINGS
FROM PRODUCTS P 
JOIN REVIEWS R 
ON P.PRODUCT_ID = R.PRODUCT_ID
GROUP BY P.PRODUCT_NAME 
HAVING AVG(R.RATING) < 3;

#WHICH USERS ARE THE MOST ACTIVE ON THE PLATFORM?
SELECT USER_ID , COUNT(*) AS AVTIVITY_COUNT
FROM EVENTS
GROUP BY USER_ID
ORDER BY AVTIVITY_COUNT DESC;

#WHICH EVENT TYPES OCCUR MOST FREQUNTLY?
SELECT EVENT_TYPE , COUNT(*) AS TOTAL_EVENTS
FROM EVENTS
GROUP BY EVENT_TYPE
ORDER BY TOTAL_EVENTS;

#WHAT PERCENTAGE OF TOTAL REVENUE COMES FROM EACH PRODUCT CATEGORY?
SELECT P.CATEGORY, SUM(OI.QUANTITY*OI.ITEM_PRICE)* 100 / (SELECT SUM(QUANTITY*ITEM_PRICE) FROM ORDER_ITEMS) AS PERCENTAGE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.CATEGORY;

#WHICH DAY GENERATED THE HIGHEST SALES?
SELECT O.ORDER_DATE , SUM(OI.QUANTITY*OI.ITEM_PRICE) AS SALES
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY O.ORDER_DATE
ORDER BY SALES DESC LIMIT 1;	


# MONTHLY TOTAL ORDERS
SELECT MONTHNAME(O.ORDER_DATE) AS MONTH_NAME , COUNT(DISTINCT O.ORDER_ID) AS ORDERS
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY  MONTHNAME(ORDER_DATE);

# DAILY TOTAL ORDERS
SELECT DAYNAME(O.ORDER_DATE) AS DAY_NAME , COUNT(DISTINCT O.ORDER_ID) AS ORDERS
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY  DAYNAME(ORDER_DATE);


#FIND THE TOP 5 PRODUCTS BY REVENUE USING A CTE
WITH PRODUCT_REVENUE AS (
    SELECT
        PRODUCT_ID,
        SUM(QUANTITY * ITEM_PRICE) AS REVENUE
    FROM ORDER_ITEMS
    GROUP BY PRODUCT_ID
)
SELECT *
FROM PRODUCT_REVENUE
ORDER BY REVENUE DESC
LIMIT 5;


#FIND CATEGORY-WISE TOTAL REVENUE
WITH CATEGORY_REVENUE AS (
    SELECT
        P.CATEGORY,
        SUM(OI.QUANTITY * OI.ITEM_PRICE) AS TOTAL_REVENUE
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P
        ON OI.PRODUCT_ID = P.PRODUCT_ID
    GROUP BY P.CATEGORY
)
SELECT *
FROM CATEGORY_REVENUE
ORDER BY TOTAL_REVENUE DESC;

