CREATE DATABASE PIZZA;
USE PIZZA;

SELECT * FROM PIZZA_DATASET;

DESCRIBE PIZZA_DATASET;

ALTER TABLE PIZZA_DATASET
ADD COLUMN ORDER_DATE_REAL DATE,
ADD COLUMN ORDER_TIME_REAL TIME;

SET SQL_SAFE_UPDATES = 0;


UPDATE PIZZA_DATASET 
SET
ORDER_DATE_REAL = STR_TO_DATE(ORDER_DATE, '%m/%d/%Y'),
ORDER_TIME_REAL = STR_TO_DATE(ORDER_TIME, '%H:%i:%s');	

ALTER TABLE PIZZA_DATASET
DROP COLUMN ORDER_DATE,
DROP COLUMN ORDER_TIME;

ALTER TABLE PIZZA_DATASET
CHANGE COLUMN ORDER_DATE_REAL ORDER_DATE DATE,
CHANGE COLUMN ORDER_TIME_REAL ORDER_TIME TIME;

#KPI

SELECT ROUND( SUM(TOTAL_PRICE),2) AS TOTAL_REVENUE
FROM PIZZA_DATASET;


SELECT SUM(QUANTITY) AS TOTAL_PIZZA_SOLD 
FROM PIZZA_DATASET;

SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_DATASET;

SELECT ROUND(SUM(TOTAL_PRICE) / COUNT(DISTINCT ORDER_ID),2) AS AVG_ORDER_VALUE
FROM PIZZA_DATASET;

SELECT SUM(QUANTITY) / COUNT(DISTINCT ORDER_ID) AS AVG_PIZZA_PER_ORDER
FROM PIZZA_DATASET;

SELECT DAYNAME(ORDER_DATE) AS DAY_NAME,COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_DATASET
GROUP BY DAYNAME(ORDER_DATE)
ORDER BY TOTAL_ORDERS;
	
SELECT MONTHNAME(ORDER_DATE) AS MONTH_NAME,COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_DATASET
GROUP BY MONTHNAME(ORDER_DATE)
ORDER BY TOTAL_ORDERS;

SELECT
pizza_category,
ROUND(
SUM(total_price) *100/
(SELECT SUM(total_price)
FROM PIZZA_DATASET),2
) AS Sales_Percentage
FROM PIZZA_DATASET
GROUP BY pizza_category;
    
    
SELECT
pizza_size,
ROUND(
SUM(total_price)*100/
(SELECT SUM(total_price)
FROM PIZZA_DATASET),2
) AS Sales_Percentage
FROM PIZZA_DATASET
GROUP BY pizza_size;

SELECT PIZZA_CATEGORY, SUM(QUANTITY) AS TOTAL_PIZZA_SOLD 
FROM PIZZA_DATASET 
GROUP BY PIZZA_CATEGORY
ORDER BY PIZZA_CATEGORY ;   

SELECT PIZZA_NAME, SUM(TOTAL_PRICE) AS REVENUE 
FROM PIZZA_DATASET 
GROUP BY PIZZA_NAME
ORDER BY REVENUE DESC
LIMIT 5;


SELECT PIZZA_NAME , SUM(TOTAL_PRICE) AS REVENUE
FROM PIZZA_DATASET
GROUP BY PIZZA_NAME
ORDER BY REVENUE ASC LIMIT 5;

SELECT PIZZA_NAME, SUM(QUANTITY) AS QUANTITY
FROM PIZZA_DATASET
GROUP BY PIZZA_NAME
ORDER BY QUANTITY DESC LIMIT 5;

SELECT PIZZA_NAME, SUM(QUANTITY) AS QUANTITY
FROM PIZZA_DATASET
GROUP BY PIZZA_NAME
ORDER BY QUANTITY ASC LIMIT 5;

SELECT PIZZA_NAME , COUNT(DISTINCT ORDER_ID) AS ORDERS
FROM PIZZA_DATASET
GROUP BY PIZZA_NAME
ORDER BY ORDERS DESC LIMIT 5;

SELECT PIZZA_NAME , COUNT(DISTINCT ORDER_ID) AS ORDERS
FROM PIZZA_DATASET
GROUP BY PIZZA_NAME
ORDER BY ORDERS ASC LIMIT 5;



